### ISSUE TITLE
Broken in 8.0

### ISSUE THREAD

**Issue by jbowensii** [winks-vtt/everybody-look#2]
PLease update this module I rely on it heavily, I am reluctant to upgrade to 8.7 until it is updated.  Thank you

**Comment by AlexOkafor** [comment]
@jbowensii It's fixed now. Foundry mods are in the process of re-listing the module, but you can do an install via the README by using this manifest URL to get the latest: `https://raw.githubusercontent.com/winks-vtt/everybody-look/master/module.json`
